#!/usr/bin/env bash

#
# CONFIG
###################
USAGE_TITLE="PXE Images Toolkit"
TITLE="Untitled"
SUBTITLE="Undefined"
## Architecture targets
AVAILABLE_ARCHES=()
TARGET_ARCHES=()
## Available Versions
KNOWN_VERSIONS=()
TARGET_VERSIONS=()
VERSION_SEPARATOR="."
## Extended Options
EXTENDED_OPTIONS=()
TARGET_OPTIONS=()
## Mirror Definitions
PROTOCOL="https"
BASE_HOST="mirror.umd.edu"
ROOT_PATH="/"
## Directory Definitions
CORE_DIR=""
DIRNAME=""
START_DIR=""
PXE_DIR="pxelinux.cfg"
## Output Generation
OUTPUT_MENU_FILE=""
## General Excludes
EXCLUDES=("boot" "lib" "pxelinux.cfg" "gparted" "memtest86" "systemrescuecd")
NULL=$(printf "%b" "\u0f")
SPACE=' '
SPACER=''
## Content
_ROOT_DIR=$(pwd)
## Style configuration
THEME_1ST=$(echo -e "${FG_GRN}")
THEME_2ND=$(echo -e "${FG_WHT}")
THEME_3RD=$(echo -e "${FG_BLU}")
THEME_4TH=$(echo -e "${FG_CYN}")
THEME_WRN=$(echo -e "${FG_YLW}")
THEME_ERR=$(echo -e "${FG_RED}")
THEME_SPACER=$(printf "%b" ${UR_DR})
THEME_BOX_DEFAULT_WIDTH=85
## Menu Filenames
MENU_IMAGES="images.menu"
MENU_DEFAULT="default.menu"
## Custom Executables
SCRIPT_UPDATE="update.sh"
## Executables
WGET="$( which wget )"
CURL="$( which curl )"
_REF_FORMAT="name|alias"

#
# USE REQUIRE (Bashful)
###################
source $( dirname -- "$0" )/lib/require.sh $*

#
# COMMANDS
###################
COMMANDS=(
  WGET
  CURL
)

#
# LIBRARIES
###################
require filesystem
require boxes
require output

#
# CUSTOM METHODS
###################
action_update () {
  dump_method $*
  local TARGET; TARGET="$1";  shift
  box_start "$( box_title "${_ROOT_DIR}" )"
  if [ -z "${TARGET}" ]; then
    output_menu_header "Images" "${_ROOT_DIR}/${MENU_IMAGES}"
    for ITEM in *; do
      if [[ -d "${ITEM}" ]] && [[ ! ${EXCLUDES[*]} =~ "${ITEM}" ]]; then
        process_dir "${ITEM}"
        if [ -f "${ITEM}/${MENU_DEFAULT}" ]; then
          output_menu_entry_include "${ITEM}/${MENU_DEFAULT}" "${ITEM}" "${_ROOT_DIR}/${MENU_IMAGES}"
        fi
      fi
      cd ${_ROOT_DIR}
    done
  else
    box_line "TARGET: ${TARGET}"
    for ITEM in ${TARGET[*]}; do
      process_dir "${ITEM}"
    done
  fi
  cd ${_ROOT_DIR}
  box_end "$( box_title "${_ROOT_DIR}" )" ${ALIGN_RIGHT}
  echo ${RESET}
}
usage_update ()     { echo "u|update ${_REF_FORMAT}"; }
describe_update ()  { echo "Update one or more image sets (ie. distributions)."; }
help_update ()      { cat << EOF

Description:
  $( describe_update)  Helper tooling for generating/updating family of PXE images.
EOF
}

action_add_client () {
  dump_method $*
  local addr;   addr="${1}";    shift
  local src;    src="${1-default}";     shift
  if [[ ! -f "${PXE_DIR}/${addr}" ]] && [[ -f "${PXE_DIR}/${src}" ]]; then
    cd "${PXE_DIR}"
    ln -s "${src}" "${addr}"
    cd ${_ROOT_DIR}
  fi
}
usage_add_client ()     { echo "a|add uuid|mac|hex-ip (template)"; }
describe_add_client ()  { echo "Add a new client to the PXE library of boot configurations."; }
help_add_client ()      { cat << EOF

Description:
  $( describe_add_client)  Helper tooling for adding new PXE client definitions.  This script will generate a symlink for the provided address to the specified template (if provided).
EOF
}
#
# PARAMETERS
###################
# Overwrite Faking
param_fake ()           { prepend_options COMMANDS "echo "; }

#
# LOGIC
###################
## Parent script for managing PXE pool of images
#
# Recursively update directory if it contains
# an update.sh script.
#
function process_dir() {
  dump_method $*
  local ITEM;     ITEM="$1";
  reset_mirror
  if [ -d "${ITEM}" ]; then
    box_start "$( box_title "${ITEM}" )"
    if [ -f "${ITEM}/${SCRIPT_UPDATE}" ]; then
      box_line "Update starting"
      box_line "${ITEM}/${SCRIPT_UPDATE}"
      source ${ITEM}/${SCRIPT_UPDATE}
      box_line "Update complete"
    else
      box_line "Update script not found"
    fi
    box_end "$( box_title "${ITEM}" )" ${ALIGN_RIGHT}
  fi
}
function reset_mirror() {
  dump_method $*
  ## Mirror Definitions
  PROTOCOL="http"
  BASE_HOST="mirror.umd.edu"
  ROOT_PATH="/"
}
#
# EXECUTION
###################
run $*